---
title: "Plot phylogenetic tree with MI + Rush VREfm genomes without controls"
output: html_document
---



```{r load packages}
library(treeio)
library(ape)
library(ggtree)
library(ggplot2)
library(heatmap3)
library(randomcoloR)
library(phytools)
library(geiger)
library(cowplot)
library(RColorBrewer)
library(geiger)
library(vcfR)

knitr::opts_chunk$set(echo = FALSE)
```


```{r load data, include=FALSE}
rush_gen = read.csv("../Rush_meta_genomics_sample_lookup/96 well map (2).csv", header = T, stringsAsFactors = F)
rush_platemap = read.csv("../Rush_meta_genomics_sample_lookup/Final Workbook WGS - MiSeq M021217 2021 Run 496 - Snitkin Graifman_platemap.csv", stringsAsFactors = F,  row.names = 1, header = T)
colnames(rush_platemap) = gsub("X", "", colnames(rush_platemap))

iqtree = read.iqtree("../genome_alignments/2021_06_12_16_42_32_Aus0004_genome_aln_w_alt_allele_unmapped_exclude_controls.treefile")

phylo = iqtree@phylo
phylo$bootstrap = phylo$node.label
phylo$node.label = c(min(phylo$edge[phylo$edge[,2] > length(phylo$tip.label),2]) - 1, phylo$edge[phylo$edge[,2] > length(phylo$tip.label),2])


```


Highlight Rush genomes by patient (correct discrepancy between plate map and well map)
```{r}
rush_gen$row = rownames(rush_gen)
rush_gen$genome_name = apply(rush_gen, 1, FUN = function(x){
  if (length(rush_gen[rush_gen$Patient.ID %in% x["Patient.ID"], "Patient.ID"]) == 1){new_name = x["Patient.ID"]}else{
    rows = rush_gen[rush_gen$Patient.ID %in% x["Patient.ID"],]
    new_name = paste0(x["Patient.ID"], "_", which(rownames(rows) %in% x['row']))
  }
  new_name
})
rush_gen$real_well_position = c(apply(rush_platemap[1:3, ], 1, FUN = function(x){x}))[1:nrow(rush_gen)]
rush_gen$real_well_position[25] = "715_3"

phylo2 = phylo
phylo2$tip.label[phylo2$tip.label %in% "715"] = "715-3"
phylo2$tip.label = sapply(phylo2$tip.label, FUN = function(i){
  if (grepl("VRE|CP", i)){tip_name = i}else{
    tip_name = rush_gen[rush_gen$real_well_position %in% gsub("-", "_", i), "genome_name"]
  }
})


###
file = paste("../figures/", format(Sys.time(), "%Y-%m-%d"), '_Michigan+Rush_VREfm_genomes_by_patient_exclude_controls_corrected_genome_name.pdf', sep = "");
pdf(file)

tipcol = structure(rep("white", length(phylo2$tip.label)), names = phylo2$tip.label)

pt_ind = sapply(names(tipcol)[grep("VRE|CP", names(tipcol), invert = T)] , FUN = function(x){print(x)
  strsplit(x, "_")[[1]][1]
})

ptcol = structure(rainbow(length(unique(pt_ind))), names= unique(pt_ind))

tip_pt_ind = sapply(names(tipcol), FUN = function(x){
  if(grepl("VRE|CP", x) == F){
  pt = strsplit(x, "_")[[1]][1]
  newcol = ptcol[pt]
  }else{newcol = tipcol[x]}
  newcol
})

phylo2$tip.label[grep("VRE|CP", phylo2$tip.label)] = ""
plot(phylo2, use.edge.length = F,edge.color = "black",  cex = 0.2, show.tip.label =T, pch =16, 
     main = "Michigan + Rush VREfm phylogeny")
tiplabels(pch = 16, col = tip_pt_ind, cex = .25, bg = tipcol)
legend("bottom", legend = c("Michigan", names(ptcol)), fill = c("blue", ptcol), cex = .5, ncol = 5, xpd = T, inset= -.1, bty = "n")

dev.off()
``` 
